-- MySQL Script generated by MySQL Workbench
-- Sáb 05 Mar 2016 16:38:24 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schedule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schedule` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `schedule` ;

-- -----------------------------------------------------
-- Table `schedule`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(100) NOT NULL COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`projeto` (
  `id` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `descricao` VARCHAR(200) NULL COMMENT '',
  `data_in` DATETIME NULL COMMENT '',
  `data_delete` DATETIME NULL COMMENT '',
  `deleted` BIT NULL COMMENT '',
  `area_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `area_id`)  COMMENT '',
  INDEX `fk_projeto_Area1_idx` (`area_id` ASC)  COMMENT '',
  CONSTRAINT `fk_projeto_Area1`
  FOREIGN KEY (`area_id`)
  REFERENCES `schedule`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`tarefa` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `descricao` VARCHAR(250) NULL COMMENT '',
  `horas` INT NULL COMMENT '',
  `data_inicio` VARCHAR(45) NULL COMMENT '',
  `deleted` BIT NULL COMMENT '',
  `data_in` DATETIME NULL COMMENT '',
  `data_delete` DATETIME NULL COMMENT '',
  `projeto_id` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `projeto_id`)  COMMENT '',
  INDEX `fk_tarefa_projeto1_idx` (`projeto_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tarefa_projeto1`
  FOREIGN KEY (`projeto_id`)
  REFERENCES `schedule`.`projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `conta_horas` BIT NULL COMMENT '',
  `data_in` DATETIME NULL COMMENT '',
  `data_delete` DATETIME NULL COMMENT '',
  `deleted` BIT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`.`status_tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`status_tarefa` (
  `status_id` INT NOT NULL COMMENT '',
  `tarefa_id` INT NOT NULL COMMENT '',
  `date_in` DATETIME NULL COMMENT '',
  `date_out` DATETIME NULL COMMENT '',
  PRIMARY KEY (`status_id`, `tarefa_id`)  COMMENT '',
  INDEX `fk_status_has_tarefa_tarefa1_idx` (`tarefa_id` ASC)  COMMENT '',
  INDEX `fk_status_has_tarefa_status_idx` (`status_id` ASC)  COMMENT '',
  CONSTRAINT `fk_status_has_tarefa_status`
  FOREIGN KEY (`status_id`)
  REFERENCES `schedule`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_has_tarefa_tarefa1`
  FOREIGN KEY (`tarefa_id`)
  REFERENCES `schedule`.`tarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `area_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `area_id`)  COMMENT '',
  INDEX `fk_email_area1_idx` (`area_id` ASC)  COMMENT '',
  CONSTRAINT `fk_email_area1`
  FOREIGN KEY (`area_id`)
  REFERENCES `schedule`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
